### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xba' in position 2819: ordinal not in range(128)

### ISSUE THREAD

**Issue by jackjackk** [dh4/pywu#2]
When running pywu fetch w/ location=IT I get this error:
```
Traceback (most recent call last):
  File "/usr/bin/pywu", line 9, in <module>
    load_entry_point('pywu==1.1', 'console_scripts', 'pywu')()
  File "/usr/lib/python3.5/site-packages/pywu/pywu.py", line 426, in main
    forecast = ForecastData(args)
  File "/usr/lib/python3.5/site-packages/pywu/pywu.py", line 174, in __init__
    self.fetch_data(apikey, location, language)
  File "/usr/lib/python3.5/site-packages/pywu/pywu.py", line 226, in fetch_data
    f.write(json_data)
UnicodeEncodeError: 'ascii' codec can't encode character '\xba' in position 2819: ordinal not in range(128)
```

**Comment by dh4** [comment]
Tell me if the latest commit fixes this issue.
