### ISSUE TITLE
SyntaxError: invalid syntax on RPI

### ISSUE THREAD

**Issue by hanthecat** [dh4/pywu#4]
Initial fetch on raspberry pi terminates with the following error when running with or without the API on the command line. Running python 2.7.9
Is there anything I can do to help?

contents of .pywu.conf
[PYWU]
apikey=<my api key>
location=New York City, NY

$ pywu fetch
Traceback (most recent call last):
  File "/usr/local/bin/pywu", line 9, in <module>
    load_entry_point('pywu==1.1', 'console_scripts', 'pywu')()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-3.5.1-py2.7.egg/pkg_resources.py", line 351, in load_entry_point
    raise TypeError("Expected string, Requirement, or Distribution", dist)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-3.5.1-py2.7.egg/pkg_resources.py", line 2363, in load_entry_point
    self._parsed_version = pv = parse_version(self.version)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-3.5.1-py2.7.egg/pkg_resources.py", line 2088, in load
    # ver. info
  File "/usr/local/lib/python2.7/dist-packages/pywu/pywu.py", line 163
    if self.verbose: print("API key and location not found in arguments, " + "trying ~/.pywu.conf", file=sys.stdout)
                                                                                                        ^
SyntaxError: invalid syntax

**Comment by hanthecat** [comment]
Installing python3 and python3-setuptools resolved issue.

**Comment by dh4** [comment]
Yes, this is specifically a python3 script. Python3 changed the syntax for several things from python2 (in this case, the print function).
